Cert
wolfSSL/wolfssh pull request #415
Opened 2022-05-23 16:22 UTC by JacobBarthelmeh

2022-08-03 17:44 UTC, JacobBarthelmeh commented
retest this

2022-08-08 23:32 UTC, JacobBarthelmeh commented
interop testing with PKIXSSH

Download pkixssh (https://roumenpetrov.info/secsh/)

Create pkixssh expected key format from john-cert.pem and john-key.pem using

```
cp ./keys/john-key.pem id_john
chmod 600 id_john
openssl x509 -in ./keys/john-cert.pem -subject -issuer -alias >> id_john
# use the pkixssh ssh-keygen tool
./ssh-keygen -y -f id_john > id_john.pub
```

Then connect to the example server using:

```
./examples/echoserver/echoserver -a ./keys/ca-ecc-cert.pem -J john:./keys/john-cert.pem

# using the pkixssh 'ssh'
./ssh -p 22222 -i id_john john@127.0.0.1
```

2022-08-24 20:04 UTC, dgarske requested changes

2022-08-24 20:04 UTC, dgarske commented on README.md
> +The echoserver and client have a fake user named "john" whose certificate
`echoserver and echoclient` or maybe `each server and client`?

2022-08-24 20:04 UTC, dgarske commented on README.md
> +    $ ./examples/echoserver/echoserver -a ./keys/ca-cert.pem
```% ./examples/echoserver/echoserver -a ./keys/ca-cert.pem
Couldn't find size of file ./keys/ca-cert.pem.```
Seems file is missing or wrong file is used here? Is it supposed to be keys/ca-ecc-cert.pem?

2022-08-24 20:04 UTC, dgarske commented on examples/client/client.c
> +#if 0
If have an `#if 0` section here please add inline code comment explaining difference. Like RSA vs ECC.

2022-08-24 20:04 UTC, dgarske commented on README.md
> +
What is an example for the client command to test this?

2022-08-29 22:51 UTC, dgarske approved these changes

2022-08-29 22:51 UTC, merged