Fixes directory listing output in sftp.
wolfSSL/wolfssh pull request #433
Opened 2022-07-29 15:57 UTC by anhu

We were only only showing the output of the first message of a directory listing
which is wrong. A directory listing can be composed of several messages so we
must keep reading until there is no more to read.

Fixes ZD14587

2022-07-29 15:58 UTC, anhu commented
@ejohnstown : Customer has indicated that there is urgent need for this fix.  Please review at your earliest convenience.

2022-07-29 16:10 UTC, anhu commented
Tested in the following manor:
In wolfssl:
```
./configure --enable-wolfssh
make all check 
sudo make install 
sudo ldconfig 
```
In wolfssh
```
./configure --enable-sftp
make all check
./examples/sftpclient/wolfsftp -h localhost -p 22 -u anthony
```
Then 
in sftp:
```
cd wolfssl/wolfcrypt/src
ls
```
Before this fix, there were 100 lines of output.
After this fix there were 162 lines of output.

2022-07-29 16:15 UTC, dgarske requested changes

2022-07-29 16:15 UTC, dgarske commented on src/wolfsftp.c
> +                } else {
```
{
else {
```

2022-07-29 16:15 UTC, dgarske commented on src/wolfsftp.c
> +                    for(runner = state->name; runner->next != NULL;
Hard to read. Use:

```
/* find end of list */
for(runner = state->name; runner->next != NULL; runner = runner->next) {};
```

2022-07-29 16:15 UTC, dgarske commented on src/wolfsftp.c
> +                        /* Error condition. Clean up previous names that we got
Is this an "error" condition? Just a non-blocking case.

2022-07-29 16:34 UTC, dgarske approved these changes

2022-07-29 17:29 UTC, dgarske commented
src/wolfsftp.c: In function ‘wolfSSH_SFTP_LS’:
src/wolfsftp.c:6081:13: error: a label can only be part of a statement and a declaration is not a statement
             WS_SFTPNAME* names = NULL;
             ^~~~~~~~~~~

2022-07-29 23:00 UTC, anhu commented
Locally reproduced the test error.  Will look into it next week.

2022-08-02 21:47 UTC, anhu commented
retest this please

2022-08-03 12:45 UTC, anhu commented
retest this please

2022-08-08 13:51 UTC, anhu commented
I believe this is ready for merging.

2022-08-08 14:57 UTC, dgarske approved these changes

2022-08-08 14:57 UTC, merged