add chroot jailing to sshd
wolfSSL/wolfssh pull request #441
Opened 2022-08-19 21:32 UTC by JacobBarthelmeh

2022-08-22 18:01 UTC, JacobBarthelmeh commented
retest this please

2022-08-27 04:11 UTC, ejohnstown requested changes
The `chroot()` call fails. When it is called, the EUID is for user sshd, which doesn't have permission to call `chroot()`. I added in a `seteuid(0);` right before calling `chroot()` and it succeeded, but we got an "[SSHD] Invalid user name found" error returned by the server.

2022-08-28 02:40 UTC, ejohnstown requested changes

2022-08-28 02:40 UTC, ejohnstown commented on apps/wolfsshd/configuration.c
> +        if (ret == WS_SUCCESS && conf->chrootDir) {
This code is duplicated down below at line 258.

2022-09-01 20:28 UTC, ejohnstown approved these changes

2022-09-01 20:28 UTC, merged