renew cert script, add check for user name in UPN and host IP in alt. names
wolfSSL/wolfssh pull request #465
Opened 2022-10-03 16:00 UTC by JacobBarthelmeh

2022-10-19 15:47 UTC, haydenroche5 requested changes

2022-10-19 20:02 UTC, haydenroche5 commented on apps/wolfsshd/auth.c
> +                                 * treatied as an error if only the user name
treatied -> treated

2022-10-19 20:32 UTC, JacobBarthelmeh commented on apps/wolfsshd/auth.c
> +                                /* UPN format is user @ domain, since currently
no spaces, correct but not explicitly the words "user" and "domain" , updated to have no spaces and use <> to show that "user" and "domain" are place holders for an actual user name and domain name

2022-10-21 16:35 UTC, haydenroche5 approved these changes

2022-10-21 16:42 UTC, ejohnstown approved these changes

2022-10-21 16:43 UTC, merged