Test Threading
wolfSSL/wolfssh pull request #474
Opened 2022-11-03 00:57 UTC by ejohnstown

1. Whitespace.
2. Threading updates
3. Improve the consistency of the asserts().
4. Improve the echoserver test driver.
5. Tweaks for Integrity.

2022-11-03 21:59 UTC, haydenroche5 requested changes

2022-11-03 21:59 UTC, haydenroche5 commented on tests/api.c
> +#ifndef WOLFSSH_NO_ASSERT_FAIL_ABORT
This name, WOLFSSH_NO_ASSERT_FAIL_ABORT, is kind of verbose and confusing. Does it just control if WABORT maps to abort? How about WOLFSSH_NO_WABORT?

2022-11-03 21:59 UTC, haydenroche5 commented
@JacobBarthelmeh would like your review before merging.

2022-11-04 21:00 UTC, haydenroche5 approved these changes

2022-11-15 20:29 UTC, JacobBarthelmeh approved these changes

2022-11-15 20:29 UTC, merged