break between SSH accept and SCP operation
wolfSSL/wolfssh pull request #519
Opened 2023-05-19 13:27 UTC by JacobBarthelmeh

setup chroot with scp operations too, breaks after SSH handshake and returns to application

2023-05-24 22:25 UTC, ejohnstown requested changes
I ran the wolfSSHd server. Then copied a file.

```
% scp -P22222 configure john@localhost:/home/john/configure
wolfSSHD
configure                                                                                         100%  633KB  17.7MB/s   00:00
```

It just hangs there.

2023-05-26 15:15 UTC, JacobBarthelmeh commented
I believe the hang with scp transfer happens in master too. When doing the Windows port of SCP I had noticed this and did a fix here (https://github.com/wolfSSL/wolfssh/pull/512/commits/d60c55b9a316a8e8fa24afaf52a441e562857cae#diff-ee22b49af3445d6389e6f9da16021ab72231506e131d6a4c357997a70fbbe061R1376)

That fix could probably be moved out of the Windows port PR though. Should it go here or in a new PR?

2023-06-01 18:25 UTC, ejohnstown commented
> I believe the hang with scp transfer happens in master too. When doing the Windows port of SCP I had noticed this and did a fix here ([d60c55b#diff-ee22b49af3445d6389e6f9da16021ab72231506e131d6a4c357997a70fbbe061R1376](https://github.com/wolfSSL/wolfssh/commit/d60c55b9a316a8e8fa24afaf52a441e562857cae#diff-ee22b49af3445d6389e6f9da16021ab72231506e131d6a4c357997a70fbbe061R1376))
> 
> That fix could probably be moved out of the Windows port PR though. Should it go here or in a new PR?

I'd put it in here, then rebase the Windows port PR when this is merged.

2023-06-02 03:54 UTC, ejohnstown approved these changes

2023-06-02 03:54 UTC, merged