RFC 8332: Part 2
wolfSSL/wolfssh pull request #525
Opened 2023-06-05 21:05 UTC by ejohnstown

Add user authentication support for RSA signing with SHA2-256 and SHA2-512.

The test I used to check the user authentication:

`./configure --enable-sftp CPPFLAGS=-DWOLFSSH_NO_SSH_RSA_SHA1 --enable-debug`

I like using SFTP to test the authentication. The flag **WOLFSSH_NO_SSH_RSA_SHA1** will disable the old and broken _ssh-rsa_ signature type. (The keys are still considered _ssh-rsa_ keys.) I used the wolfsftp example command:

`./examples/sftpclient/wolfsftp -u john -h localhost -p 22 -i ~/priv.der -j ~/pub.txt`

The keys _priv.der_ and _pub.txt_ are just for this test:

```
openssl genrsa -out priv.pem 2048
openssl rsa -in priv.pem -outform der -out priv.der
ssh-keygen -y -f priv.pem >pub.txt
cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup
cat ~/.ssh/authorized_keys.backup pub.txt >~/.ssh/authorized_keys
```

Shortly after the log message listing the user authentication types the server accepts, you should see:

`2023-06-21 19:51:43 [DEBUG] User signature type: rsa-sha2-256`

2023-06-15 07:55 UTC, JacobBarthelmeh approved these changes

2023-06-20 17:11 UTC, dgarske requested changes
Can you add a test case or document how to test it?

2023-06-22 02:53 UTC, ejohnstown commented
The test I used to check the user authentication:

`./configure --enable-sftp CPPFLAGS=-DWOLFSSH_NO_SSH_RSA_SHA1 --enable-debug`

I like using SFTP to test the authentication. The flag **WOLFSSH_NO_SSH_RSA_SHA1** will disable the old and broken _ssh-rsa_ signature type. (The keys are still considered _ssh-rsa_ keys.) I used the wolfsftp example command:

`./examples/sftpclient/wolfsftp -u john -h localhost -p 22 -i ~/priv.der -j ~/pub.txt`

The keys _priv.der_ and _pub.txt_ are just for this test:

```
openssl genrsa -out priv.pem 2048
openssl rsa -in priv.pem -outform der -out priv.der
ssh-keygen -y -f priv.pem >pub.txt
cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup
cat ~/.ssh/authorized_keys.backup pub.txt >~/.ssh/authorized_keys
```

Shortly after the log message listing the user authentication types the server accepts, you should see:

`2023-06-21 19:51:43 [DEBUG] User signature type: rsa-sha2-256`

2023-06-22 16:02 UTC, dgarske requested changes
Great work on this. Looks great and tests out. I noticed a few places where the code uses a word32 val = sizeof() that you might consider a refactor to handle implicit cast.

2023-06-22 22:04 UTC, ejohnstown commented on src/internal.c
> +#define EXTENSION_COUNT 1
Check.

2023-06-22 22:04 UTC, ejohnstown commented on src/internal.c
> +const char serverSigAlgsName[] = "server-sig-algs";
Check.

2023-06-23 16:55 UTC, dgarske approved these changes

2023-06-23 16:55 UTC, merged