Support large file sizes in long file names.
wolfSSL/wolfssh pull request #548
Opened 2023-07-21 08:04 UTC by falemagn

2023-07-27 22:02 UTC, JacobBarthelmeh commented
ok to test

2023-07-28 15:07 UTC, JacobBarthelmeh requested changes

2023-07-28 15:07 UTC, JacobBarthelmeh commented on src/wolfsftp.c
> +    sprintf(size, "%8lld", ((long long int)atr->sz[1] << 32) + (long long int)(atr->sz[0]));
please use WSNPRINTF here

2023-08-08 16:14 UTC, JacobBarthelmeh approved these changes

2023-08-21 12:46 UTC, falemagn commented
Can this be merged?

2023-08-22 22:19 UTC, SparkiDev approved these changes

2023-08-22 22:19 UTC, merged