wolfSSH Client
wolfSSL/wolfssh pull request #586
Opened 2023-09-20 01:35 UTC by ejohnstown

Phase 1 of the wolfSSH client.

2023-09-20 17:04 UTC, JacobBarthelmeh requested changes

2023-09-20 17:04 UTC, JacobBarthelmeh commented on apps/wolfssh/wolfssh.c
> +            appName);
Help menu should show what -V is (verbose debug? version?)

2023-09-22 22:20 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +            appName);
I'm following the options as displayed by ssh. We don't support `-abcdef` strings of options, though. I should have "destination" in there.

2023-09-22 22:21 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +THREAD_RETURN WOLFSSH_THREAD client_test(void* args)
Done.

2023-09-22 22:27 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +    if (strlen(reqStr) == sz
We need some refactoring of the API compatibility layer soon. The file handling needs an overhaul.

2023-09-22 22:46 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +        if (ret != 0) {
This should work now.

2023-09-24 21:18 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +    if (strlen(reqStr) == sz
Done.

2023-09-24 21:18 UTC, ejohnstown commented on apps/wolfssh/wolfssh.c
> +            appName);
Added it to the readme file.

2023-09-25 16:07 UTC, JacobBarthelmeh commented
Please resolve this build `./configure --enable-sshclient --disable-term` now that a recent fix for --disable-term was added. (or throw error in configure if that's an invalid build)

2023-09-25 19:29 UTC, JacobBarthelmeh approved these changes

2023-09-25 19:29 UTC, merged