Made setting file modes portable
wolfSSL/wolfssh pull request #616
Opened 2023-11-09 11:11 UTC by falemagn

Made setting file modes portable, by means of defining the WOLFSSH_SFTP_SETFILEMODE and WOLFSSH_SFTP_SETMODE macros, in which case the functions SFTP_SetMode and SFTP_SetFileMode will have to be externally defined for the platform the library is being ported to.

2023-11-15 20:13 UTC, JacobBarthelmeh commented
Ok to test

2023-11-17 00:50 UTC, ejohnstown requested changes

2023-11-17 00:50 UTC, ejohnstown commented on src/wolfsftp.c
> +    WOLFSSH_UNUSED(fs)
Missing ;

2023-11-17 00:50 UTC, ejohnstown commented on src/wolfsftp.c
> +    WOLFSSH_UNUSED(fs)
Missing ;

2023-12-05 00:07 UTC, ejohnstown approved these changes

2023-12-05 18:48 UTC, merged