SSHD Banners
wolfSSL/wolfssh pull request #720
Opened 2024-07-08 17:08 UTC by ejohnstown

# DESCRIPTION

Add support for loading banner files into wolfSSHd.

# TESTING

Add "Banner filename.txt" to the sshd_config file used by wolfSSHd.

2024-07-15 22:31 UTC, JacobBarthelmeh requested changes

2024-07-15 22:31 UTC, JacobBarthelmeh commented on apps/wolfsshd/wolfsshd.c
> +        freeBufferFromFile(*banner, NULL);
This should be in the config for the specific user I think. To handle something like this in the future:

```
Match User sshUser
    Banner /path/to/specific_banner
```

2024-07-15 22:37 UTC, JacobBarthelmeh commented on apps/wolfsshd/wolfsshd.c
> +        freeBufferFromFile(*banner, NULL);
Opps sorry, looks like it is setup that way. Just init/free different than I expected. Please double check the XFREE call though after CleanupCTX (with *banner set to NULL here).

2024-07-16 20:43 UTC, douzzer approved these changes

2024-07-16 20:43 UTC, merged