keep trailing delimiter with SFTP path clean
wolfSSL/wolfssh pull request #743
Opened 2024-09-30 21:54 UTC by JacobBarthelmeh

ZD 18566

Fix for SFTP cases with trailing delimiter. i.e

OpenSSH client 9.6 (which does a SFTP command instead of SCP, -O restores using SCP protocol)
```
mkdir /tmp/subfolder
scp /tmp/test.txt jill@127.0.0.1:/tmp/subfolder/test/
```

Before this change wolfSSH would allow test.txt to be copied to /tmp/subfolder/test. After this change the command correctly fails as.

2024-10-10 20:19 UTC, JacobBarthelmeh commented on src/internal.c
> +        out[curSz] = 0;
sanity checks needed on curSz before use (thanks @douzzer )

2024-10-15 05:21 UTC, douzzer requested changes

2024-10-15 05:21 UTC, douzzer commented on src/internal.c
> +        }
As discussed, when `*outSz` is to small to accommodate the shifted data with the terminating null, an error code should be returned, and checked for by callers.

2024-11-01 17:57 UTC, dgarske approved these changes

2024-11-01 19:23 UTC, douzzer approved these changes

2024-11-01 19:24 UTC, merged