wolfSSH support for using TPM based key for authentication
wolfSSL/wolfssh pull request #754
Opened 2024-12-13 00:09 UTC by aidangarske

# Description 

wolfSSH tpm support using client side public key authentication with rsa. Refer to the readme for testing steps and more information. Code working just like the non tpm public key authentication.

2024-12-13 22:55 UTC, dgarske requested changes
Various errors building without TPM:

```
src/ssh.c:1810:15: error: call to undeclared function 'wc_PubKeyPemToDer'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = wc_PubKeyPemToDer(in, inSz, newKey, newKeySz);
              ^
src/ssh.c:1810:15: note: did you mean 'wc_KeyPemToDer'?
/Users/runner/work/wolfssh/wolfssh/build-dir/include/wolfssl/wolfcrypt/asn_public.h:692:21: note: 'wc_KeyPemToDer' declared here
    WOLFSSL_API int wc_KeyPemToDer(const unsigned char* pem, int pemSz,
                    ^
1 error generated.
make[1]: *** [src/libwolfssh_la-ssh.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/internal.c:12950:25: error: unused variable 'sigSz' [-Werror,-Wunused-variable]
                    int sigSz;
                        ^
1 error generated.
```

2024-12-17 19:54 UTC, dgarske requested changes

2024-12-17 19:54 UTC, dgarske commented on src/ssh.c
> +        long e;
This should only occur if `!isPrivate`. Make sure the old isPrivate code still returns the `*out = newKey;` etc.

2024-12-26 18:49 UTC, dgarske requested changes
This PR is very close to ready. Let's change it to use endorsement primary key are parent to avoid the SRK handle/auth.

2024-12-26 18:49 UTC, dgarske commented on examples/client/common.c
> +static const char gStorageKeyAuth[] = "ThisIsMyStorageKeyAuth";
The SRK handle and password being hard coded is not good. Both of these should be macros wrapped with `#ifndef` at a minimum. Ideally they would be arguments to the example client or not needed at all.

If I were writing this example I would create the key using the endorsement primary key... then you would not need anything related to the SRK... It's a pretty easy change, mostly to your README.md to create the key under the endorsement hierarchy using `-eh`.

2025-03-27 21:36 UTC, dgarske requested changes

2025-03-27 21:36 UTC, dgarske commented on configure.ac
> +AS_IF([test "x$ENABLED_SMALLSTACK" = "xyes"],
Rebase error. Lines 240-241 need removed. Duplicated above at 232-233.

2025-03-27 21:36 UTC, dgarske commented on README.md
> +    $ ./examples/client/client -i ../wolfTPM/keyblob.bin -u hansel -s pk
Needs updated. Removed SRK option and the `-s pk` isn't there anymore.

2025-03-27 21:36 UTC, dgarske commented on examples/client/common.c
> +#ifndef WOLFSSH_TPM_KEY_AUTH
The password used needs to be optional and provided at the command line. Please change wolfTPM keygen to allow not using a password or using a custom one like this: `./examples/keygen/keygen keyblob.bin -rsa -t -pem -eh -auth=custompass`. Then the SSH client should default to no password or allow one like this: `./examples/client/client -i ../wolfTPM/keyblob.bin -u hansel -p custompass`.

2025-03-28 21:00 UTC, aidangarske commented on examples/client/common.c
> +#ifndef WOLFSSH_TPM_KEY_AUTH
I have added a -K argument where you can specify the password and updated the readme so that you can either just use the "ThisIsMyKeyAuth" with the default keygen or supply your own password to the keygen and add the password to the -K argument.

2025-03-28 21:17 UTC, dgarske requested changes
PR is great! Please add a GitHub CI action test based on the READM.md. That way this can be tested continuously to make sure it doesn't break.

2025-04-01 23:51 UTC, dgarske requested changes

2025-04-01 23:51 UTC, dgarske commented on .github/workflows/tpm-ssh.yml
> +        ssh-keygen -f key.pem -i -m PKCS8 > ../wolfssh/key.ssh
Use a different filename so you can save both artifacts.

2025-04-01 23:51 UTC, dgarske commented on .github/workflows/tpm-ssh.yml
> +        pkill -f tpm_server
Killing server and waiting is not required. Please remove. If you want it please make a separate build step

2025-04-01 23:51 UTC, dgarske commented on examples/echoserver/echoserver.c
> +    FILE* file;
Please use the port.h macros. WFILE, WFSEEK, etc.

2025-04-02 04:59 UTC, aidangarske commented on examples/echoserver/echoserver.c
> +    FILE* file;
Sounds good, I have used the port.h macros for this now.

2025-04-02 14:26 UTC, dgarske requested changes

2025-04-02 14:26 UTC, dgarske commented on examples/client/common.c
> +    XFILE  fp = NULL;
Please switch to using the wolfSSH file porting macros `WFILE` and `WFOPEN`. This is using the wolfSSL ones.

2025-04-02 14:26 UTC, dgarske commented on examples/echoserver/echoserver.c
> +    buffer = (char*)WMALLOC(length + 8 + 1, NULL, DYNTYPE_BUFFER);
Please pass "hansel" as argument. Then allocate extra for it and copy.

2025-04-02 18:23 UTC, dgarske approved these changes

2025-04-02 18:23 UTC, merged